# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Styx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Styx
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'SwiftMessages'
  pod 'SCLAlertView'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'EZLoadingActivity'
  pod 'SideMenu'
  pod 'DLRadioButton', '~> 1.4'
  
end
